### ISSUE TITLE
[feature request] enhanced auto-load and recent

### ISSUE THREAD

**Issue by dyphire** [mpvnet-player/mpv.net#454]
Add a option to only add same series of videos. Please refer to https://github.com/mpv-player/mpv/pull/8563.
Add a option or a command palette to realize that only the latest playback files in the same directory are displayed in recent list.

This isn't a high priority request.

**Comment by stax76** [comment]
What exactly do you mean with same series of videos?

I usually don't spend time adding special functionality, users have to find or write a script.

**Comment by dyphire** [comment]
> What exactly do you mean with same series of videos?

Similar to those mentioned in the comments https://github.com/mpv-player/mpv/pull/8563#issuecomment-1079760870
It refers more to the videos of episodes with similar file names.
Because mpvnet implements the file loading function by itself, this may not be implemented by script alone.

As mentioned at the beginning, these requests for enhancements are not high priority.
So it's not too late to think about it when you're interested.

**Comment by stax76** [comment]
To use in mpv.net, users can disable `auto-load-folder` and use a modified autoload.lua script.

What I do very often in such cases is scripting with [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher) or [Open with++](https://github.com/stax76/OpenWithPlusPlus), I use powershell, but any language can be used. Open with++ allows creating a "Play related files with mpv.net" or "Append related files to mpv.net playlist", in Open with++ you select only one file and the script finds the related files.

There is also this:

https://github.com/ikas-mc/ContextMenuForWindows11

Personally, I prefer the old menu because it is faster and visually easier to use.

![Screenshot (27)](https://user-images.githubusercontent.com/11410540/178156787-3bf9015d-8faa-4980-9ddf-3cef35725515.png)

**Comment by dyphire** [comment]
> To use in mpv.net, users can disable `auto-load-folder` and use a modified autoload.lua script.

True, but it would be better if mpv.net could realize similar functions.

**Comment by stax76** [comment]
I used to integrate such kind of request in staxrip, hundreds, maybe thousands, for 20 years, but there is only so much open source somebody can do. Nowadays, I focus on popular basics and what I like or use personally.

**Comment by dyphire** [comment]
> I added two new loading logics One is the same type (image video...) One is the same file ext
> 
> There are even new process-instance Can exist multiple mpv at the same time without interfering with each other One for video and one for audio
> 
> But its implementation is rather ugly... I put a specific identifier after the title Then when a new search process is opened to determine if it contains an identifier...
> 
> See more ( The article is in Chinese)
> 
> https://meta.appinn.net/t/topic/35444

Your modification is not related to these functions of this issue request, but I will look at it.

**Comment by dyphire** [comment]
Replace with #575
