### ISSUE TITLE
MAUI Support

### ISSUE THREAD

**Issue by michalss** [mpvnet-player/mpv.net#499]
Hi is there ant way this could work on MAUI, cross all platform's please?

**Comment by stax76** [comment]
I use Linux as main OS since a couple of weeks. Next is a small web scraping project, so not mpv related. No plans beyond that, in general I focus on learning, which includes cross-platform GUI topics.

**Comment by stax76** [comment]
Some clarification, Linux is not supported by MAUI and even if it had Linux support, it wouldn't be suitable for a mpv frontend on Linux because a mpv frontend must directly interface with an X11 window, so for the main windows even Avalonia is not suitable. It's complicated, C# might not be the best choice for a Linux frontend because on Linux Rust is already much more popular. GTK4 would be suitable, but there aren't C# bindings for GTK4 and .NET 6 I believe, for Rust bindings exist and are well maintained. I will certainly continue to investigate the idea.

**Comment by theChaosCoder** [comment]
Alternative to MAUI would be: https://avaloniaui.net

**Comment by michalss** [comment]
> Alternative to MAUI would be: https://avaloniaui.net

What this has to do with this project? Im looking for cross platform player where i can import subtitles, and where player supports many formats.

**Comment by theChaosCoder** [comment]
> 
> Im looking for cross platform player where i can import subtitles, and where player supports various formats.

VLC?
> What this has to do with this project?

Do you mean .net MAUI or KDE MAUI?

**Comment by stax76** [comment]
There seem to be a project working on C# GTK bindings:

https://github.com/gircore/gir.core

The main window needs to embed an X11 video window, info here:

https://mpv.io/manual/master/#options-wid

It needs a modern light/dark context menu, and if possible embed a command palette child window, all other windows can be done with Avalonia.

**Comment by michalss** [comment]
> There seem to be a project working on C# GTK bindings:
> 
> https://github.com/gircore/gir.core
> 
> The main window needs to embed an X11 video window, info here:
> 
> https://mpv.io/manual/master/#options-wid
> 
> It needs a modern light/dark context menu, and if possible embed a command palette child window, all other windows can be done with Avalonia.

see i would include this project to on my own. Im working on simillar application like kodi. Pretty much done with all features, so all its left is some good videoplayer...

**Comment by User-3090** [comment]
If you really consider a Rust rewrite, take a look at how Gyroflow does it with QT.
