### ISSUE TITLE
What happened with mpv.net-next? The github page is down

### ISSUE THREAD

**Issue by ThomasEricB** [mpvnet-player/mpv.net#519]
https://github.com/mpv-net-player/mpv.net-next

**Comment by stax76** [comment]
I often change plans, the current plan is supporting Linux, but I didn't yet do a lot to get there, what I did so far is developing a small private .NET CLI project called trash-tracker, on Linux, it helps me to learn to develop .NET on Linux and get accustomed to it, I use VS Code as IDE. I use trash-tracker for finding new music, it keeps track of what I already listened to. Currently, I improve this project since I search new music every day. 

Some days ago I explored the AvaloniaUI source code a bit, it's the UI framework that I want to use to develop mpv.net Linux support, I hope it will work out because a mpv GUI has some special/uncommon requirements.

Most of the time, I work on small scripts and tools I need myself and don't have much time after that. On Windows, I used a large and complex powershell script that makes backups of all my data, it's using robocopy and I want to port it to Linux, using rsync instead of robocopy, so I don't need to boot into Windows when I want to make a backup.

I still have my Windows 11 system, in case an important mpv.net issue appears, I can work on it easily.

That's the current situation with mpv.net. 🙂
