### ISSUE TITLE
Release executables with different publish settings?

### ISSUE THREAD

**Issue by zhongfly** [mpvnet-player/mpv.net#571]
**Is your feature request related to a problem? Please describe.**
As a result of the migration to .net 6, more settings can be choosen when publishing executable.For example: single-file, self-contained, ReadyToRun.
It might be a good idea to choose as few combinations of options as possible to distribute the executable, both to satisfy the needs of different people and not to confuse new users.

**Describe the solution you'd like**
I perfer:
* single file + no self-contained + ReadyToRun (without libmpv.dll or mediainfo.dll): only 2MB+ , user need to install .net 6 but get smaller size and single file.
* single-file + self-contained + ReadyToRun (with libmpv.dll and mediainfo.dll): 150MB+dlls size, user don't no need to install .net 6, just click to run.(ps: this is not a really single file, but enable single-file for smaller size.)

**Additional context**
https://learn.microsoft.com/en-us/dotnet/core/deploying/
https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run

**Comment by zhongfly** [comment]
Also, consider not releasing 32-bit anymore. After all, it's rare to see 32-bit Windows these days.

**Comment by stax76** [comment]
I don't think using ReadyToRun or Release builds would have a noticeable performance benefit, I did some benchmarking and research in the past. There is a performance problem in the conf editor, which can be addressed with a rewrite I need to do in order to add more options, options that excite users like libplacebo options. Working with WPF is however difficult, so I don't know if and when I do this rewrite.

Self-contained is often considered as bloat, trimming would shrink the size significantly but does not work with WPF, unfortunately.

Single file has its appeal, it can be assumed that it's something that users prefer, so it makes sense using it, mpv/libmpv is also a single file, which I like too.

**Comment by stax76** [comment]
I rewrote my release script today from scratch using the dotnet publish single file option and the GitHub CLI client to release it. A new beta version is online.
