### ISSUE TITLE
Bring back microsoft store build of mpv.net

### ISSUE THREAD

**Issue by soredake** [mpvnet-player/mpv.net#615]
**Is your feature request related to a problem? Please describe.**
Microsoft store version have advantages over winget/scoop/chocolatey packages:

1. Problems like this will not happen in msstore package https://github.com/qbittorrent/qBittorrent/issues/18582
2. You don't need to manually add mpv.net to PATH
3. You don't need to manually register Audio/Video associations.
4. No "smart screen" warning before launch
![image](https://github.com/mpvnet-player/mpv.net/assets/5204968/e7565828-603e-4515-a9e2-a1627c9e3941)
5. No UAC is needed to install mpv.net
![UAC_User_Account_Control_Prompt_Example](https://github.com/mpvnet-player/mpv.net/assets/5204968/74545527-0bd2-4f27-bdf1-3c726a70ae86)

**Describe the solution you'd like**
Bring back mpv.net to microsoft store, maybe this project will help https://github.com/SilverEzhik/mpv-msix

**Describe alternatives you've considered**
Using `mpv-msix`

**Additional context**

**Comment by candrapersada** [comment]
Even though mpv.net returns to the Microsoft Store, you still have to install or use the .NET Desktop Runtime

**Comment by soredake** [comment]
@candrapersada .net runtime can be bundled into exe like in this software https://www.nexusmods.com/batmanarkhamasylum/mods/117?tab=files (i don't care about size increase honestly)

**Comment by Witchilich** [comment]
To be frank scoop already automatically adds it to path.

**Comment by 9ao9ai9ar** [comment]
As a reference, both Krita and MKVToolNix release their programs onto the Microsoft Store for a fee to fund their projects while also providing traditional installation means for free. A Microsoft Store version of mpv.net would not be without disadvantages however:

1. The Microsoft Store is neither available nor officially supported on Windows Server and Windows IoT/Enterprise editions (so is winget at the moment).
2. Because the installation directory changes with each update, it is a hassle to add firewall rules to store apps (might or might not be relevant to mpv.net).
3. [The Microsoft Store does not provide APIs to interface with scripts](https://github.com/microsoft/windows-dev-box-setup-scripts/issues/30), so automation is harder (there is [Appx-Backup](https://github.com/mjmeans/Appx-Backup) but that looks like a lot of work).
4. You have to follow the Microsoft Store policies, for better or worse.

I've also looked into scoop/winget/chocolatey, and they each have their own strengths and weaknesses. I try to summarize them succinctly:

1. Scoop is PowerShell friendly and is especially suited for installing CLI applications, but there is zero automated testing and malware scanning done on its apps, and `scoop virustotal` was unusable for me even with an API key for some reason.
2. WinGet benefits from being an official Microsoft product, but as mentioned earlier it is only available on consumer versions of Windows, and feature-wise is not as good as scoop.
3. Chocolatey is the only one that actually does dependency management so is often slower, but it feels old-school.

My personal preference would be MSI/MSIX, followed by EXE then WinGet, the two current solutions.
