### ISSUE TITLE
Open URL or file path from clipboard in queue mode from Context Menu Commands without changing process-instance=single

### ISSUE THREAD

**Issue by candrapersada** [mpvnet-player/mpv.net#621]

**Comment by candrapersada** [comment]
and is there an option to save playlists as m3u/m3u8 files?

**Comment by stax76** [comment]
Both mpv and mpv.net have only a minimal feature set and rely on user scripts even for common features.

This script is very popular:

https://github.com/jonniek/mpv-playlistmanager

If this doesn't work, you can try:

https://github.com/stax76/awesome-mpv

Ideally, such features exist, the problem is building it isn't easy, I mean not just this particular feature, but building a feature rich application in general.

**Comment by candrapersada** [comment]
how to use Open URL or file path from clipboard in queue mode from Context Menu?

**Comment by stax76** [comment]
mpv uses the shift key for drag and drop:

> --drag-and-drop=<no|auto|replace|append>
> Controls the default behavior of drag and drop on platforms that support this. auto will obey what the underlying os/platform gives mpv. Typically, holding shift during the drag and drop will append the item to the playlist. Otherwise, it will completely replace it. replace and append always force replacing and appending to the playlist respectively. no disables all drag and drop behavior.

I can add support for shift key to append when using drag and drop and the clipboard import.

Also see here:

https://github.com/stax76/mpv-scripts/blob/main/misc.lua#L26

**Comment by candrapersada** [comment]
https://github.com/mpvnet-player/mpv.net/blob/764f00ed3a0e6687f40dbaece68b9715f9fa12fe/docs/manual.md?plain=1#L736

**Comment by Sneakpeakcss** [comment]
> and is there an option to save playlists as m3u/m3u8 files?


```lua
-- save-open-playlist.lua
local utils = require 'mp.utils'

-- MPC-HC .mpcpl playlist
local function load_mpcpl_playlist(playlist_file)
    local file = io.open(playlist_file, "r")
    for line in file:lines() do
        if string.match(line, "^%d+,filename,") then
            local path = string.gsub(line, "^%d+,filename,", "")
            local path = path:gsub("\r", "")
            mp.commandv("loadfile", path, "append-play")
        end
    end
    file:close()
end

mp.add_key_binding(nil, "load_playlist", function()
    local open = utils.subprocess({playback_only=false, args={"powershell", "-NoProfile", "-Command", [[
        Add-Type -AssemblyName System.windows.forms;
        $f = [System.Windows.Forms.OpenFileDialog]::new();
        $f.Filter = "Playlist files (*.mpv.m3u8, *.mpcpl, *.m3u, *.m3u8)|*.mpv.m3u8;*.mpcpl;*.m3u;*.m3u8|All files (*.*)|*.*";
        $f.Multiselect = $true;
        $f.ShowDialog() | Out-Null;
        $utf8 = New-Object System.Text.UTF8Encoding $false;
        [Console]::OutputEncoding = $utf8;
        $f.FileNames -join "`n"
    ]]}})
    local playlist_files = open.stdout
    local single_playlist = true
    for playlist_file in string.gmatch(playlist_files, '([^\n]+)') do
        playlist_file = playlist_file:gsub("\r", "")
        if playlist_file ~= "" then
            mp.msg.info("Loading playlist from file: " .. playlist_file)
            local load_type = single_playlist and "replace" or "append"
            if string.match(playlist_file, "%.mpcpl$") then
                load_mpcpl_playlist(playlist_file)
            else
                mp.commandv("loadlist", playlist_file, load_type)
            end
            single_playlist = false
        end
    end
end)

-- Add playlist without overwritting current one
mp.add_key_binding(nil, "append_playlist", function()
    local open = utils.subprocess({playback_only=false, args={"powershell", "-NoProfile", "-Command", [[
        Add-Type -AssemblyName System.windows.forms;
        $f = [System.Windows.Forms.OpenFileDialog]::new();
        $f.Filter = "Playlist files (*.mpv.m3u8, *.mpcpl, *.m3u, *.m3u8)|*.mpv.m3u8;*.mpcpl;*.m3u;*.m3u8|All files (*.*)|*.*";
        $f.Multiselect = $true;
        $f.ShowDialog() | Out-Null;
        $utf8 = New-Object System.Text.UTF8Encoding $false;
        [Console]::OutputEncoding = $utf8;
        $f.FileNames -join "`n"
    ]]}})
    local playlist_files = open.stdout
    for playlist_file in string.gmatch(playlist_files, '([^\n]+)') do
        playlist_file = playlist_file:gsub("\r", "")
        if playlist_file ~= "" then
            mp.msg.info("Loading playlist from file: " .. playlist_file)
            if string.match(playlist_file, "%.mpcpl$") then
                load_mpcpl_playlist(playlist_file)
            else
                mp.commandv("loadlist", playlist_file, "append")
            end
        end
    end
end)

mp.add_key_binding(nil, "save_playlist", function()
    local playlist = {}
    local count = mp.get_property_number("playlist-count")
    for i = 0, count - 1 do
        local path = mp.get_property(string.format("playlist/%d/filename", i))
        table.insert(playlist, path)
    end

    local save = utils.subprocess({args={"powershell", "-NoProfile", "-Command", [[
	Add-Type -AssemblyName System.windows.forms;
	$f = [System.Windows.Forms.SaveFileDialog]::new();
	$f.FileName = "playlist";
	$f.DefaultExt = "mpv.m3u8";
	$f.Filter = "mpv Playlist files (*.mpv.m3u8)|*.mpv.m3u8|All files (*.*)|*.*";
	$f.ShowDialog() | Out-Null;
	$utf8 = New-Object System.Text.UTF8Encoding $false;
	[Console]::OutputEncoding = $utf8;
	$filename = $f.FileName
	if (-not ($filename.EndsWith(".mpv.m3u8"))) {$filename += ".mpv.m3u8"}
	$filename
    ]]}})
    local playlist_file = save.stdout:gsub("\r\n", "")	-- Remove trailing newline and carriage return characters
    if playlist_file ~= "" then
        mp.msg.info("Saving playlist to file: " .. playlist_file)
        local file = io.open(playlist_file, "w")
        for _, path in ipairs(playlist) do
            file:write(path .. "\n")
        end
        file:close()
    end
end)

```
`input.conf`
```
_	    script-message-to save_open_playlist save_playlist  	#menu: Open > Save playlist...
_	    script-message-to save_open_playlist load_playlist  	#menu: Open > Open playlists...
_	    script-message-to save_open_playlist append_playlist  	#menu: Open > Append playlists...
_           script-message-to mpvnet open-files  append  		#menu: Open > Add files to playlist...
```


Unfortunately for drag+drop both `mpv` and `mpv.net` have the same behaviour where dropping multiple playlists/folders only loads contents from the first one that autoplays, so it only expands additional ones when either playback reaches the folder/playlist or when opened manually beforehand, it's really annoying when you want to load multiple and use `play-random` for all files.

This script autoexpands all playlists automatically when opened through dialog window, should also work with `MPC-HC` .mpcpl playlists.

___
 

As a sidenote… For some reason when using the mentioned above contexmenu keybinds, `mpv.net` suddenly displays the `_` sign for the last defined option when using old `#menu:` syntax. 
In comparison from what i've seen the new `#custom-menu` always displays this "empty" keybind, but in case of `#menu:` it would be expected to work like in any other `_` keybind and never show it ? Maybe it has something to do with adding two `script-message-to` to the same submenu and bugging it out.

![image](https://github.com/mpvnet-player/mpv.net/assets/77424331/300a13fa-c07f-4446-aac3-0b8ab6c7d2a9)

**Comment by stax76** [comment]
I checked it in the debugger, and it turned out there are `\t` tab characters. Next build replaces them with spaces before parsing the file.

**Comment by candrapersada** [comment]
@Sneakpeakcss
how to use Open URL or file from clipboard in queue mode for mpv non mpv.net?

**Comment by Sneakpeakcss** [comment]
`Open > Add files to playlist...` from what i know is just a context menu version of the same action as drag+drop over the window, it just always appends selected files rather than overwritting the playlist, so in a way it's similar to `Append playlists` from my script, the difference being that you can add any file, either video/audio/playlist/etc files. 

`Open URL or file from clipboard` is the same action as the default(?) `ctrl+v` hotkey that [opens](https://github.com/mpvnet-player/mpv.net/blob/86c823bfdecbcf716ee7c4484b2057a6b31f5ece/src/MpvNet.Windows/GuiCommand.cs#L154) the file when a valid path was copied beforehand to clipboard:

```
C:/test/test.mp4
file://C:/test/test.mp4
https://www.youtube.com…
```
I barely ever use that because it's way faster to just drag+drop files over the player, so the only use case for me is just loading youtube links, and that's mostly by using the binding for it. 
That context menu option i can only assume is for completion/discovery sake, because i cannot imagine it being quicker in any way than `ctrl+v`, and from what i know it only allows a single path at once. 

Though, based on the recent [change](https://github.com/mpvnet-player/mpv.net/commit/764f00ed3a0e6687f40dbaece68b9715f9fa12fe#diff-6a134cfd07d7311732c69be74ca751459948db77e599870222cd1bf432bd0b58) mentioned [above](https://github.com/mpvnet-player/mpv.net/issues/621#issuecomment-1868245797), it now allows appending files to playlist while holding `shift`, so i assume that in this case it only works for context menu because pressing `shift+ctrl+v` would be a different hotkey, potentially one that's already binded to something else in `input.conf` <sub> (or potentially a future bug report if it actually works in this case and doesn't take the same binding into consideration lol)</sub>

I don't use "queue mode" and i'm not even certain what does this refer to exactly, because the only "queue" that seems in any way significant to all of this would be the `process-instance` which seems to be a `mpv.net` exclusive option, and based on its description both of the mentioned `Open` actions work exactly as i would expect them in that mode, and any other mode for the matter. Beyond that i have no clue.

**Comment by stax76** [comment]
@Sneakpeakcss

You are right that using the shift key to alter the behavior of commands creates issues. I reverted adding files from clipboard with shift key and instead did this:

- New menu item and binding: `File > Add files to playlist from clipboard` `Ctrl+Shift+v`.

`Ctrl+Shift+v   script-message-to mpvnet open-clipboard append  #menu: File > Add files to playlist from clipboard`

`open-clipboard` supporting an `append` flag is new.
