### ISSUE TITLE
Window sometimes opens "twice" on Windows

### ISSUE THREAD

**Issue by mnervik** [mpvnet-player/mpv.net#671]
**Describe the bug**
Sometimes when opening the player, or double clicking a video when and the video gets openened in the player you get two windows instead of just 1.

**To Reproduce**
1. Open the player
2. Close the window fast if only a single window appear
3. Repeat step 1 until it happens
4. If it does not happen, double click on a some media to open some media, then repeat step 2

**Expected behavior**

**Screenshots**
Current behaviour
![image](https://github.com/mpvnet-player/mpv.net/assets/89079512/8fc707de-ab50-4969-acd1-9dedfbab9c8d)

Expected behaviour
![image](https://github.com/mpvnet-player/mpv.net/assets/89079512/2826522e-213a-4b57-9b16-b22d3a23cc93)

**Additional context**
1. mpv.net version: 7.1.1.0
2. Windows version: Windows 10.0 (build 19045)
3. GPU name: AMD 6750 XT
4. Media info: None (issue is also there when no media is played)

**Comment by stax76** [comment]
Do you shut down the machine daily, maybe it could be an issue discussed [here](https://github.com/mpv-player/mpv/issues/10189)?

A problem I have myself might be caused by a user script that uses JSON IPC, for instance a remote control script. Seeing a list with all user scripts installed might help with this issue.

Maybe it's more likely to happen on the very first start after a reboot, this start is slower, which might trigger the issue.

**Comment by mnervik** [comment]
Rebooting my system seems to have fixed the issue
