### ISSUE TITLE
"Unknown property: 'video-aspect'" since upgrading to 7.x

### ISSUE THREAD

**Issue by FasterRider** [mpvnet-player/mpv.net#707]
I just upgraded from 6.x and have the same problem with both v7.1.1.1-beta and v7.1.1.0: Pressing A for aspect ratio as I've been used to for a long time brings up: "Unknown property: 'video-aspect'". I can't change aspect ratio via the menu either. I tried both portable and installer. As I doubt this feature has been removed in 7.x - how do I get it back? Thanks!

(I'd also like to have the old app icon back, but I doubt that's possible...)

**Comment by stax76** [comment]
It's due to a mpv change:

It used to be:

`cycle-values video-aspect 16:9 4:3 2.35:1 -1`

Now it is:

`cycle-values video-aspect-override 16:9 4:3 2.35:1 0 -1`

https://mpv.io/manual/master/#options-video-aspect-override

mpv and mpv.net users that have the old name in their input.conf have to fix it by manually editing input.conf.

**Comment by FasterRider** [comment]
Done, thanks!
